platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.11-alpine3.8
inputs:
  - name: http-smoke-tests-git
run:
  path: sh
  args:
  - -euc
  - |
    export GOPATH=$PWD
    cd http-smoke-tests-git
    go test -v ./...
